#! /bin/sh

###############
## autostart ##
###############

## hotkey daemon ##
sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc &

## lunch polybar
~/.config/polybar/scripts/launch_polybar.sh &

## picom compositor ##
picom --experimental-backends --config "$HOME"/.config/picom/picom.conf &

## set wallpaper ##
feh --bg-scale "$HOME"/.config/wallpapers/000001.jpg

## launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 & }

## fixing the cursor ##
xsetroot -cursor_name left_ptr

## fast key movement ##
xset r rate 200 50

##################
## bspwm config ##
##################

bspc monitor -d 󰖟 󰳫         

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52

bspc config single_monocle	 true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 15

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"
bspc config presel_feedback_color "#23252e"

#################
## bspwm rules ##
#################

bspc rule -a Pavucontrol state=floating center=on rectangle=760x500+0+0
bspc rule -a Timeshift-gtk state=floating center=on
bspc rule -a Virt-manager state=floating desktop='^7' rectangle=1200x700+0+0 follow=on center=on
